### ISSUE TITLE
not able to full portrait screen full .

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#13]
Hi dear developer , 
I am using your player but it does not supporting full screen display as default of portrait mode . can you help me to achieve this

**Comment by lzls** [comment]
You can refer to issues #8 for a solution

**Comment by waqasyousafy** [comment]
how can i detect the portrait videos and landscap videos ?

**Comment by lzls** [comment]
@waqasyousafy patch for this has been uploaded into [#8](https://github.com/lzls/Videos/issues/8#issuecomment-1238285596) just now.
