### ISSUE TITLE
Can not show hidden folder video like- com.thunderdog.org/files/video

### ISSUE THREAD

**Issue by AdityaMishra135** [lzls/Videos#15]

**Comment by lzls** [comment]
Hidden videos and videos under a hidden folder are not recorded to the system db. and they usually mean non-public files, so ignore.

**Comment by AdityaMishra135** [comment]
But some app save files in there package dir.

**Comment by lzls** [comment]
> But some app save files in there package dir.

In this case, the files in the package dir (including the pkg dir) are only visible to the owner app. Other apps can not access them directly unless it shares the video file through Intent action SEND or requests to play the video in another app through Intent action VIEW.
