### ISSUE TITLE
add drawer background default/reset option

### ISSUE THREAD

**Issue by AdityaMishra135** [lzls/Videos#17]
Add clear background option in drawer background.

**Comment by lzls** [comment]
I just have been hesitating about where the option should be placed so a little bit lazy. As a feasible alternative, you can set a usless picture for the drawer background and then delete the pic from Photos on your phone. Last to achieve that aim, restart the app. Ahahaha...

**Comment by lzls** [comment]
This option was add in commit  https://github.com/lzls/Videos/commit/b2106678fc74cdcae6f92b74ced748b5961f4c33, so issue closes.
