### ISSUE TITLE
playback speed issue , video and audio not matching if change the speed ?

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#19]
Hi ,
when i change the playback speed , audio and video are not matching each other . Also i have seen that audio is ended and video is still continuing . 
Please help me .

**Comment by lzls** [comment]
Which player did you use？Will this happen same on other videos in your phone? If not so，I think it is just because the video is of poor support by the player you selected.

**Comment by waqasyousafy** [comment]
ijk player i am using , it happens on most of videos

**Comment by lzls** [comment]
Could you please send me any of the videos？Does it be normal when you watch them using the other players？

**Comment by waqasyousafy** [comment]
i am not using other players 
you can check with small short videos like tiktok downloaded videos

**Comment by waqasyousafy** [comment]
did you check that ?

**Comment by lzls** [comment]
Sorry, I have not encountered this situation. I think it is very likely the ijkpalyer's issue so I can not fix it...
