### ISSUE TITLE
Black screen on ,if you pause the video and minimize app then again brows at front  black screen remain .

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#20]
I am using ijk player when i pause the video and by click home button for minimize it and then come back from recent it shows black screen . How can it resolve it , it should show video frame . but black screen is showing instead . please help .

**Comment by lzls** [comment]
This is normal, because the video will be closed to release related resources when you press the home key and a previously paused video will not be automatically opened the next time the app switches to the foreground. But if you toggle the audio to play in background option on, no black screen should come.

**Comment by waqasyousafy** [comment]
I am seeing in other players their surface view not got black . I want to show surface view (video view )   if the video paused  and come from recent .

**Comment by lzls** [comment]
@waqasyousafy see this sumarry:

> This is normal, because the video will be closed to release related resources when you press the home key and a previously paused video will not be automatically opened the next time the app switches to the foreground. But if you toggle the `Allow audio to play in background` option on and comment the `onVisibilityAggregated()` mehod of `TextureVideoView` out to keep the Surface used for displaying the videos unchanged, no black screen should come.

**Comment by waqasyousafy** [comment]
does nothing i have commented all code in onvisibilityaggregated()

**Comment by lzls** [comment]
You should also not close the video (i.e., not release the IjkPlayer) when app switches to the background.
