### ISSUE TITLE
Video stuck on big video when seek by user ?

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#21]
I am using ijk player part of your player. If i seek video  forward or backward video stuck for some time and then play. I want to fix it. Can you guide me about it .Thanks in advance

**Comment by lzls** [comment]
This is because the accurate seek option has been enabled for [IjkVideoPlayer](url) (see line 296–297),

> // Enable accurate seek
        ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);

which results in more time needed by the player to precisely seek to the desired video playback position if the video only has a few I frames.

**Comment by waqasyousafy** [comment]
can i change the behavior to fast and not stuck the video 
i have noted that video is buffered successfully but not seek to required position .

**Comment by lzls** [comment]
Just to replace

>ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);

with

>ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 0);
mIjkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "fflags", "fastseek");

**Comment by waqasyousafy** [comment]
I am facing issue with seeking .  If i drag the video to 20sec  player seeking it to 17sec . or if i seek to 3sec  player seeking it to 0 sec.
