### ISSUE TITLE
Seekbar abnormal behavior ?

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#25]
I am facing issue with seeking . If i drag the video to 20sec player seeking it to 17sec . or if i seek to 3sec player seeking it to 0 sec.

I am getting this issue the difference of seeking is sometime is 2 sec and sometime is 3 sec . I really worried about the abnormal behavior of player .
I have added these two parameters to ijkplayer

            ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 0);
            ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "fflags", "fastseek");

if I add 

     ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);

then video stuck for while when seeking to seek to exact point .

Any help ?

**Comment by lzls** [comment]
This is normal, because you have used fast seek on IjkPlayer, which will not guranteen that the final playback position will be exactly as you expected if at the point the video frame is not an I frame.

**Comment by lzls** [comment]
This relates to the issue #21

**Comment by waqasyousafy** [comment]
what is solution for that i seek fast and accurate ? what do you suggest ?

**Comment by lzls** [comment]
This is impossible for any players unless the video has more I frames which however will also increase the video size. Just use the precise seek which I think does not have any problems.

**Comment by waqasyousafy** [comment]
https://github.com/bilibili/ijkplayer/issues/2087 i have seen it but not working with your code

**Comment by waqasyousafy** [comment]
> This is impossible for any players unless the video has more I frames which however will also increase the video size. Just use the precise seek, instead, which I think does not have any obvious problems.

My videos are stucking on small devices like oppoa 37f  . I have to remove this stucking , other players are doing it fine.

**Comment by waqasyousafy** [comment]
If we set  

      ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);

accurate seekbar for small videos 


and for big videos 


      ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);

it will be fine behavior .

**Comment by lzls** [comment]
> If we set
> 
> ```
>   ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
> ```
> 
> accurate seekbar for small videos
> 
> and for big videos
> 
> ```
>   ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
> ```
> 
> it will be fine behavior .

Are they the same solution to small and big videos?

**Comment by waqasyousafy** [comment]
> If we set
> 
> ```
>   ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
> ```
> 
> accurate seekbar for small videos
> 
> and for big videos
> 
> ```
>   ijkPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 0);
> ```
> 
> it will be fine behavior .

big and small videos are on behalf of total duration
