### ISSUE TITLE
textureview shows previouse video frame ?

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#26]
When i play next video  textureview shows previous video frame and shows newly played video .  I want to fix it . Please help me .

**Comment by waqasyousafy** [comment]
how to clear last frame in texturevideoview am getting issue of this please help me

**Comment by lzls** [comment]
We have no mean to clear the last video frame shown on TextureView. I have already written code to make it invisible before new video starts, but this does not help too much (See TextureVideoView [L4055](https://github.com/lzls/Videos/blob/v2.1.1-beta02/texture-video-view/src/main/java/com/liuzhenlin/texturevideoview/TextureVideoView.java#L4055), [L1918-L1932](https://github.com/lzls/Videos/blob/v2.1.1-beta02/texture-video-view/src/main/java/com/liuzhenlin/texturevideoview/TextureVideoView.java#L1918-L1932) and [L4092](https://github.com/lzls/Videos/blob/v2.1.1-beta02/texture-video-view/src/main/java/com/liuzhenlin/texturevideoview/TextureVideoView.java#L4092))

**Comment by waqasyousafy** [comment]
I have checked them but not working in ijk video player .

**Comment by waqasyousafy** [comment]
if we change 

 @Override
    void onVideoSizeChanged(int width, int height) {
        mTextureView.setAlpha(0);
        counter = 0;
        checkButtonsAbilities();
        Log.d("pausetr", "onVideoSizeChanged" + counter);

        if (width != 0 && height != 0) {
            requestLayout();
        }

    } 

and 


 @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surface) {


                if (counter > 5) {
                    mTextureView.setAlpha(1);

                }
                counter++;
            }


then it will not show last frame of last played video and also show next video view  .
