### ISSUE TITLE
video stucking on show controls on touch in 6.0.1  android ?

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#28]
In video player i have set controls . when the video is playing with show controls . it is stucking  a lot also dropping frames. I need help please help me . device is oppo A57a . Any help ?

If i comment this line  
  sendEmptyMessage(MSG_REFRESH_VIDEO_PROGRESS); 

then video progress not updating or video playing fine . how can i fix it.

**Comment by lzls** [comment]
You should use sendEmptyMessageDelayed() just as my code does. I have test the app in Android 5.1.1. There does not exist this problem.

**Comment by waqasyousafy** [comment]
no , but in showControls() method seekbar refreshing callback freezing video .
