### ISSUE TITLE
audio focus issue 

### ISSUE THREAD

**Issue by waqasyousafy** [lzls/Videos#30]
our player never get the audiofocus . when other player vide is playing our player video got stopped . but when our is playing then other player video not getting stoped. how to fix it lzls. please respond

**Comment by lzls** [comment]
You should call mAudioManager.requestAudioFocus(mAudioFocusRequest) when video playback starts. See [IjkVideoPlayer (line 447–453)](https://github.com/lzls/Videos/blob/4ca38dd76fd382f867181deb0d35fb7cbe604e40/texture-video-view/src/main/java/com/liuzhenlin/texturevideoview/IjkVideoPlayer.java#L447-L453)

**Comment by waqasyousafy** [comment]
AUDIOFOCUS_REQUEST_GRANTED  called every time video play but other player does not stop play .

**Comment by lzls** [comment]
Maybe the other palyer does not intended to stop playback when its OnAudioFocusChangeListener receives AudioManager.AUDIOFOCUS_LOSS event.

**Comment by waqasyousafy** [comment]
i think so because i have seen the playit  video player it is not stoping the video while when we play our video in our player . 
is it good or bad behavior .

**Comment by waqasyousafy** [comment]
lzls please respond on my online video question

**Comment by lzls** [comment]
The other player Is designed so, even though it behaves not the same way as the most media applications.

**Comment by waqasyousafy** [comment]
check my online video question plz
