### ISSUE TITLE
After rename folder name not update 

### ISSUE THREAD

**Issue by AdityaMishra135** [lzls/Videos#37]
![Screenshot_2024-05-11-08-36-56-327_com liuzhenlin videos](https://github.com/lzls/Videos/assets/94228705/9cc1df4a-908f-4ab2-bd56-097208619505)
Renamed name is Instagrah
![Screenshot_2024-05-11-08-37-06-345_com liuzhenlin videos](https://github.com/lzls/Videos/assets/94228705/26a197e6-2d55-45a2-be00-c845d725bced)
But it's actual dir name original dir name. Renaming function not changing their original path name

**Comment by lzls** [comment]
The renaming function for a video dir is designed so. It is just to make an alias for the directory, without any modification to the actual dir path.
