### ISSUE TITLE
About changing url？

### ISSUE THREAD

**Issue by candice1205** [lzls/Videos#7]
hello, sorry, thank you very much for providing such a complete code, but I can’t find out where to change the url of the online video. Can anyone who knows please tell me?

**Comment by lzls** [comment]
The data of the online video list comes from https://gitee.com/lzl_s/Videos-Server/raw/master/tvs.json, but most of the online video links are invalid for now. You can update the list by providing another tvs.json with some different contents.

**Comment by lzls** [comment]
Also, you can provide your own way to load the data onto the online video list:
The [OnlineVideoListModel](https://github.com/lzls/Videos/blob/release/app/src/main/java/com/liuzhenlin/videos/model/OnlineVideoListModel.kt) fetches the data for the list from the remote server and fill them into a set of data classes.
The [OnlineVideosFragment](https://github.com/lzls/Videos/blob/release/app/src/main/java/com/liuzhenlin/videos/view/fragment/OnlineVideosFragment.kt)  binds the fetched data onto the list to show and to interact with the user events (click, long click, etc.).

**Comment by candice1205** [comment]
> Also, you can provide your own way to load the data onto the online video list:
> The [OnlineVideoListModel](https://github.com/lzls/Videos/blob/release/app/src/main/java/com/liuzhenlin/videos/model/OnlineVideoListModel.kt) fetches the data for the list from the remote server and fill them into a set of data classes.
> The [OnlineVideosFragment](https://github.com/lzls/Videos/blob/release/app/src/main/java/com/liuzhenlin/videos/view/fragment/OnlineVideosFragment.kt) binds the fetched data onto the list to show and to interact with the user events (click, long click, etc.).

thank you so much, I will try it, if you have any questions, I will trouble you

**Comment by lzls** [comment]
OK. ==
