### ISSUE TITLE
Can you please make the video player landscape or portrait by default so that the blank screen should not come! 

### ISSUE THREAD

**Issue by salman660** [lzls/Videos#8]

**Comment by salman660** [comment]
[https://github.com/ApksHolder/Videos/raw/master/screenshot_04.jpg](url)

**Comment by lzls** [comment]
You can simply change the parameter passed for `setFullscreenMode()` from `mVideoView.isInFullscreenMode()` to `true` in the `onAttachedToWindow()` method of `VideoActivitity`.

**Comment by lzls** [comment]
Then the video will be fullscreened by default.

**Comment by salman660** [comment]
thanks
